<a href="https://colab.research.google.com/github/Oliver226698/Machine-learning/blob/master/Copy_of_artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# 要調整國家這欄變數
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
# OneHotEncoding的欄位會跑到前面去
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
# ANN是sequential的,像是layers是從input -> hidden layers -> output這種概念, 所以這段程式碼可以建立ANN
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
# 可以加入各種layer
# tf.keras.layers.Dense()的units是代表Neurons數量, 至於要放幾個Neurons要測試才知道
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [0]:
# 因為dependence variable是0&1，所以units=1就好，若今天是Classificaton，有ABC三個
# activation function用sigmoid因為這樣結果可以用percentage呈現
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
# 要輸入三個參數,optimizer(最適化方法,ex:gradient descent), loss:損失函數, evaluation metrics:評估模型
# 這邊是binary classfication所以loss='binary_crossentropy', 講者說如果是category形式要用loss='catagorical_crossentropy'
# metrics可以同時用很多種
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics =['accuracy'])

### Training the ANN on the Training set

In [25]:
# batch_size會比較有效率，不用一個yhat跟一個actual value去比較，可以一群一群比
# batch_size的default值是32,這邊是為了介紹
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4731 - accuracy: 0.8033
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4376 - accuracy: 0.8090
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4243 - accuracy: 0.8129
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4169 - accuracy: 0.8151
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4116 - accuracy: 0.8192
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4074 - accuracy: 0.8200
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4041 - accuracy: 0.8226
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4011 - accuracy: 0.8239
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3986 - accuracy: 0.8253
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3961 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [30]:
len(X[0])

12

In [48]:
# 重要點之一：predict()中要放進array,所以要有兩個[](會產生1個2D array),
# 重要點之二：小心Geography & Gender已經被轉換了
# 重要點之三：要記得scale輸入值，ANN需要把feature做標準化，不能忘記!!
ann_pred = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
# 預測出來結果是customer不會離開銀行, threshold這邊就設0.5,可以自己調整
print(ann_pred > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [49]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [51]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1526   69]
 [ 212  193]]


0.8595